name: Python Folder Monitor

on:
  push:
    branches:
      - main  # Menjalankan workflow setiap kali ada perubahan pada branch "main"
  pull_request:
    branches:
      - main  # Menjalankan workflow saat ada pull request ke branch "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Menggunakan image Ubuntu di GitHub Actions

    steps:
    # Langkah 1: Checkout kode dari repositori
    - name: Checkout code
      uses: actions/checkout@v2

    # Langkah 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Versi Python yang akan digunakan (sesuaikan jika diperlukan)

    # Langkah 3: Install dependensi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependensi yang terdaftar di requirements.txt

    # Langkah 4: Jalankan skrip Python untuk memantau folder
    - name: Run folder monitor script
      run: python monitor_folder.py 
